
spring:
  datasource:
    sql-script-encoding: utf-8 # 解决中文乱码
    username: lhw
    password: 12345678
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521/ORCL
    druid:
      #filters: stat,wall,log4j,config
      initial-size: 3
      max-active: 200
      min-idle: 3
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-open-prepared-statements: 50
      remove-abandoned: true
      remove-abandoned-timeout: 180
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 3000s
    lettuce:
      pool:
        max-active: -1  #最大活跃连接数，为-1时表示不限制
        max-idle: 50    #最大空闲数
        max-wait: -1    #等待可用连接的最大时间，-1为不限制
        min-idle: 0     #最小空闲数
  cache:
    redis:
      time-to-live: 6000
logging:
  level:
    com.scitc.cache.mapper: debug

server:
  port: 8900
  servlet:
    context-path: /redisDemo

#springfox:
#  documentation:
#    swagger-ui:
#      enabled: true

swagger:
  enabled: true
